# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'file_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\" \n\x0b\x46ileRequest\x12\x11\n\tdirectory\x18\x01 \x01(\t\"!\n\x10\x46ileListResponse\x12\r\n\x05\x66iles\x18\x01 \x03(\t\"\x1c\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\x1e\n\x0cUploadStatus\x12\x0e\n\x06status\x18\x01 \x01(\t2j\n\x0b\x46ileService\x12.\n\tListFiles\x12\x0c.FileRequest\x1a\x11.FileListResponse\"\x00\x12+\n\nUploadFile\x12\n.FileChunk\x1a\r.UploadStatus\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=22
  _globals['_FILEREQUEST']._serialized_end=54
  _globals['_FILELISTRESPONSE']._serialized_start=56
  _globals['_FILELISTRESPONSE']._serialized_end=89
  _globals['_FILECHUNK']._serialized_start=91
  _globals['_FILECHUNK']._serialized_end=119
  _globals['_UPLOADSTATUS']._serialized_start=121
  _globals['_UPLOADSTATUS']._serialized_end=151
  _globals['_FILESERVICE']._serialized_start=153
  _globals['_FILESERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
